#!/bin/bash
DAT=$(git ls-files | cut -d/ -f1-2 | grep -E '^[[:digit:]]+/.+' | sort | uniq | while read line; do if [[ -d "$line" ]]; then echo "$line"; fi; done)
MAX_DAY=$(echo "$DAT" | cut -d'/' -f1 | sort -nr | head -n1)
MAX_DAY=${MAX_DAY##0}
LANGS=$(echo "$DAT" | cut -d'/' -f2 | sort | uniq | grep -v utils)
LONGEST_LANG=$(echo "$LANGS" | awk '{print length}' | sort -nr | head -n1)

printf "%-${LONGEST_LANG}s                   |1|1|1|1|1|1|1|1|1|1|2|2|2|2|2|2|" "" | head -c$((LONGEST_LANG + MAX_DAY*2 + 2))
echo
printf "%-${LONGEST_LANG}s |1|2|3|4|5|6|7|8|9|0|1|2|3|4|5|6|7|8|9|0|1|2|3|4|5|" "" | head -c$((LONGEST_LANG + MAX_DAY*2 + 2))
echo

for lang in $LANGS; do
    printf "%-${LONGEST_LANG}s " $lang
    echo -n "|"
    for day_raw in `seq 1 $MAX_DAY`; do
        day=$(printf "%02d" $day_raw)
        if   [[ -e ./$day/$lang/sol1 && -e ./$day/$lang/sol2 ]]; then echo -n "█|";
        elif [[ -e ./$day/$lang/sol1 ]]; then echo -n "░|";
        elif [[ -e ./$day/$lang/sol2 ]]; then echo -n "▒|";
        else echo -n " |";
        fi
    done
    echo
done
